name: pita

services:
  nextjs:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - localstack

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}

  localstack:
    image: localstack/localstack:s3-latest
